# Generated by Django 4.2.6 on 2023-10-30 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0024_color_code_size_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='pro_variant',
        ),
        migrations.AddField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='items.products'),
        ),
    ]
